services:
  db:
    image: postgres:15
    restart: always
    container_name: matchme-db

    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASENAME}
    ports:
      - '5432:5432'
volumes:
  pgdata:
